# Generated by Django 3.1.3 on 2021-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210825_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
