# Generated by Django 3.1.3 on 2021-08-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_posted',
        ),
    ]
