# Generated by Django 3.1.3 on 2021-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='def.jpg', upload_to='media/profile'),
        ),
    ]
