# Generated by Django 4.2.1 on 2023-05-26 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='event_catagorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.TextField(max_length=200)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('date', models.DateTimeField()),
                ('educational_leave', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField()),
                ('catagorey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.event_catagorey')),
                ('orginzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgnizer', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
