# Generated by Django 4.2.1 on 2023-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_event_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.TextField(default='', max_length=200),
        ),
    ]
