# Generated by Django 4.2.1 on 2023-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_event_location_event_city_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='Online', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.TextField(default='', max_length=20),
        ),
    ]
